services:
  - type: web
    name: neonboost-backend
    env: node
    region: Oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: neonboost2024
      - key: DISCORD_WEBHOOK_URL
        value: https://discord.com/api/webhooks/1479995906592870475/xrH8_iONyIOq5cD1TE1YWwFGmjuj90kdGDgZnWMepqAsbHbJqNCw7NbnQiAVAHYP4ldt
      - key: BANK_BOG_ACCOUNT
        value: GE15BG0000000900450000
      - key: TBC_BANK_ACCOUNT
        value: GE29TB0110000060701234
