services:
  - type: web
    name: neonboost-backend
    env: node
    region: Oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: neonboost2024
      - key: TELEGRAM_BOT_TOKEN
        value: 8598410253:AAEHZo0nkfYevliirAkn3ZFPGd3isRkMRT8
      - key: TELEGRAM_CHAT_ID
        value: "6409902444"
      - key: APP_URL
        value: https://neonboost-backend.onrender.com
      - key: BANK_BOG_ACCOUNT
        value: GE15BG0000000900450000
      - key: TBC_BANK_ACCOUNT
        value: GE29TB0110000060701234
